export interface Card {
    artist:string;
    cmc:number;
    colorIdentity:Array<string>;
    colors:Array<string>;
    flavor:string;
    foreignNames:Array<string>;
    id:string;
    imageUrl:string;
    layout:string;
    legalities:Array<string>;
    manaCost:string;
    multiverseid:string;
    name:string;
    number:string;
    originalText:string;
    originalType:string;
    power:string;
    printings:Array<string>;
    rarity:string;
    set:string;
    setName:string;
    subtypes:Array<string>;
    text:string;
    toughness:string;
    type:string;
    types:Array<string>;
}